export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const EDIT_PROFILE = 'EDIT_PROFILE'

export const ADD_ORGANISATION = 'ADD_ORGANISATION'
export const GET_ORGANISATIONS = 'GET_ORGANISATIONS'
export const EDIT_ORGANISATION = 'EDIT_ORGANISATION'
export const GET_ORGANISATION = 'GET_ORGANISATION'

export const ADD_USER = 'ADD_USER'
export const GET_USERS = 'GET_USERS'
export const EDIT_USER = 'EDIT_USER'
export const GET_USER = 'GET_USER'
export const DELETE_USER = 'DELETE_USER'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const GET_CATEGORY = 'GET_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'