export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const ADD_ORGANISATION = 'ADD_ORGANISATION'
export const GET_ORGANISATIONS = 'GET_ORGANISATIONS'
export const EDIT_ORGANISATION = 'EDIT_ORGANISATION'
export const GET_ORGANISATION = 'GET_ORGANISATION'