export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'

export const ADD_ORG = 'ADD_ORG'
export const SET_ORGANISATIONS = 'SET_ORGANISATIONS'
export const SET_ORGANISATION = 'SET_ORGANISATION'
export const SET_MODIFIED_ORG = 'SET_MODIFIED_ORG'

export const SET_USERS = 'SET_USERS'
export const SET_USER = 'SET_USER'
export const SET_MODIFIED_USER = 'SET_MODIFIED_USER'

export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_MODIFIED_CATEGORY = 'SET_MODIFIED_CATEGORY'

export const SET_DISCS = 'SET_DISCS'
export const SET_DISC = 'SET_DISC'
export const SET_MODIFIED_DISC = 'SET_MODIFIED_DISC'

export const SET_VMS = 'SET_VMS'
export const SET_VM = 'SET_VM'
export const SET_MODIFIED_VM = 'SET_MODIFIED_VM'